project_id = "yodgjxdekuraxquxkxhx"

[functions.webhook-gateway]
verify_jwt = false

[functions.webhook-zapi]
verify_jwt = false

[functions.agent-chat]
verify_jwt = false

[functions.scrape-url]
verify_jwt = false