[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = ['bun install --no-frozen-lockfile']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run preview --host 0.0.0.0 --port $PORT'
