[phases.setup]
nixPkgs = ['nodejs', 'bun']

[phases.install]
cmds = ['rm -f bun.lockb', 'bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run preview --host 0.0.0.0 --port $PORT'
