import {
  Bot,
  GitBranch,
  MessageSquare,
  MessageCircle,
  Mic,
  FileText,
  Zap,
  CalendarClock,
  User,
  Info,
  Phone as PhoneIcon,
  Upload,
  PackageCheck,
  Globe,
  Database,
  Link2,
  Plus,
  X,
  Mail,
  Users,
  ArrowRight,
  RefreshCw,
  Sparkles,
  Eye,
} from "lucide-react";
import { BaseBlockOption } from "./AddBlockDialog";

export const BLOCKS_AVAILABLE: BaseBlockOption[] = [
  // AGENTES IA
  {
    type: "agenteIA",
    label: "Agente IA",
    icon: Bot,
    description: "Agente autônomo que conversa e usa ferramentas",
    category: "Agentes IA",
  },
  {
    type: "blocoCondicao",
    label: "Roteador",
    icon: GitBranch,
    description: "Direciona o fluxo com base na conversa",
    category: "Agentes IA",
  },

  // ENVIO DE MENSAGENS
  {
    type: "blocoConteudo",
    label: "Conteúdo",
    icon: MessageSquare,
    description: "Enviar mensagem de texto, mídia ou arquivo",
    category: "Envio de Mensagens",
  },
  {
    type: "blocoConteudo",
    label: "Mensagem de Texto",
    icon: MessageCircle,
    description: "Envia resposta em texto para o lead",
    category: "Envio de Mensagens",
  },
  {
    type: "blocoConteudo",
    label: "Mensagem em Áudio",
    icon: Mic,
    description: "Envia um arquivo de áudio para o lead",
    category: "Envio de Mensagens",
    extraData: { contentType: "audio" },
  },
  {
    type: "blocoConteudo",
    label: "ElevenLabs Audio",
    icon: Mic,
    description: "Áudio com voz premium ElevenLabs",
    category: "Envio de Mensagens",
  },
  {
    type: "blocoConteudo",
    label: "Mensagem Predefinida",
    icon: FileText,
    description: "Mensagem fixa sem processamento IA",
    category: "Envio de Mensagens",
  },
  {
    type: "blocoAcao",
    label: "Digitando",
    icon: MessageSquare,
    description: "Exibe \"digitando...\" por 5 segundos",
    category: "Envio de Mensagens",
    extraData: { actionType: "typing", typingDuration: 5 },
  },
  {
    type: "blocoConteudo",
    label: "Template WhatsApp Oficial",
    icon: FileText,
    description: "Envia template aprovado por dispositivo (sessão fechada)",
    category: "Envio de Mensagens",
  },

  // DECISÕES E CONDICIONAIS
  {
    type: "blocoCondicao",
    label: "Condição",
    icon: GitBranch,
    description: "Criar ramificações no fluxo",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Condição If/Else",
    icon: GitBranch,
    description: "Múltiplas saídas baseadas em condições",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Condição IF",
    icon: GitBranch,
    description: "Se verdadeiro continua, se falso para",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Split",
    icon: GitBranch,
    description: "Divide fluxo em caminhos paralelos",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Decisão por Tags",
    icon: GitBranch,
    description: "Direciona baseado nas tags do lead",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Decisão por Horário",
    icon: CalendarClock,
    description: "Direciona por horário de funcionamento",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Filtro por Cadastro",
    icon: User,
    description: "Filtra por campos personalizados do lead",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Filtro por Mensagem",
    icon: MessageCircle,
    description: "Filtra pela última mensagem do lead",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Filtro por Status do Atendimento",
    icon: Info,
    description: "Direciona por status: na fila, humano, agente ou finalizado",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Filtro por Sessão WhatsApp",
    icon: PhoneIcon,
    description: "Verifica sessão aberta/fechada em dispositivo oficial",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Filtro por Follow Up",
    icon: GitBranch,
    description: "Direciona se a task veio de mensagem follow up (status 11)",
    category: "Decisões e Condicionais",
  },
  {
    type: "blocoCondicao",
    label: "Comprovante de Pagamento",
    icon: Upload,
    description: "Para o fluxo e aguarda envio de comprovante (imagem/PDF)",
    category: "Decisões e Condicionais",
    extraData: { 
      variable: "mensagem", 
      dataType: "string", 
      operator: "contains",
      compareValue: "[media:", 
      isProofBlock: true
    },
  },

  // ENTREGÁVEIS
  {
    type: "agentTool",
    label: "Entregáveis",
    icon: PackageCheck,
    description: "Envia os conteúdos após o pagamento ser confirmado",
    category: "Entregáveis",
    extraData: { 
      toolName: "entregaveis",
      label: "Entregáveis",
      description: "Envia os conteúdos (vídeo, foto, documento, texto) após o pagamento ser confirmado",
      category: "Conhecimento",
      instructions: "Use IMEDIATAMENTE após confirmar que o pagamento do lead foi aprovado. Envie todos os entregáveis configurados (vídeos, fotos, documentos, áudios e textos) na ordem definida, com legendas/instruções apropriadas. Confirme com o lead se recebeu tudo e ofereça suporte para acessar o conteúdo."
    },
  },

  // FERRAMENTAS DE INTEGRAÇÃO
  {
    type: "blocoAcao",
    label: "Ação",
    icon: Zap,
    description: "Executar uma ação específica",
    category: "Ferramentas de Integração",
  },
  {
    type: "blocoAcao",
    label: "Chamada de API",
    icon: Globe,
    description: "Requisição HTTP direta (GET, POST, PUT, DELETE)",
    category: "Ferramentas de Integração",
  },

  // PERSISTÊNCIA DE DADOS
  {
    type: "blocoAcao",
    label: "Memória de Atendimento",
    icon: Database,
    description: "Salva dados temporários do atendimento atual",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Memória de Lead",
    icon: Database,
    description: "Salva no cadastro do lead (permanente)",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Memória de Projeto",
    icon: Database,
    description: "Salva dados globais do projeto (todos os leads)",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Resumo de Conversa",
    icon: FileText,
    description: "Cria resumo dos atendimentos e compacta o chat atual quando necessário",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Adicionar Tags",
    icon: Plus,
    description: "Adiciona tags ao cadastro do lead",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Remover Tags",
    icon: X,
    description: "Remove tags do cadastro do lead",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Atualizar Lead",
    icon: User,
    description: "Atualiza campos do cadastro do lead",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Criar Registro CRM",
    icon: Plus,
    description: "Cria negócio, ticket ou tarefa no CRM",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Listar Dados CRM",
    icon: Database,
    description: "Lista negócios, tickets, transações e outros recursos do lead",
    category: "Persistência de Dados",
  },
  {
    type: "blocoAcao",
    label: "Vincular Recurso CRM",
    icon: Link2,
    description: "Cria associação entre dois recursos do CRM",
    category: "Persistência de Dados",
  },

  // GATILHOS
  {
    type: "blocoGatilho",
    label: "Gatilho",
    icon: Key,
    description: "Palavra-chave que dispara o fluxo",
    category: "Gatilhos",
  },

  // CONTROLE DE FLUXO
  {
    type: "blocoAgendamento",
    label: "Agendamento",
    icon: CalendarClock,
    description: "Agendar envio para data/hora específica",
    category: "Controle de Fluxo",
  },
  {
    type: "blocoAcao",
    label: "Delay",
    icon: CalendarClock,
    description: "Aguarda tempo antes de continuar",
    category: "Controle de Fluxo",
  },
  {
    type: "blocoAcao",
    label: "Adicionar Msg ao Chat",
    icon: MessageCircle,
    description: "Monta mensagem com variáveis dinâmicas",
    category: "Controle de Fluxo",
  },
  {
    type: "blocoAcao",
    label: "Enviar Email",
    icon: Mail,
    description: "Monta e envia email com variáveis dinâmicas",
    category: "Controle de Fluxo",
  },

  // FINALIZAÇÃO
  {
    type: "blocoAcao",
    label: "Trocar Departamento",
    icon: Users,
    description: "Envia lead para outro departamento",
    category: "Finalização",
  },
  {
    type: "blocoAcao",
    label: "Direcionar para Fila",
    icon: ArrowRight,
    description: "Coloca na fila do departamento atual",
    category: "Finalização",
  },
  {
    type: "blocoAcao",
    label: "Trocar Estratégia",
    icon: RefreshCw,
    description: "Transfere para outra estratégia/robô",
    category: "Finalização",
  },
  {
    type: "blocoAcao",
    label: "Finalizar Atendimento",
    icon: X,
    description: "Encerra o atendimento do lead",
    category: "Finalização",
  },
  {
    type: "blocoAcao",
    label: "Fim do Fluxo",
    icon: X,
    description: "Ponto final do processamento",
    category: "Finalização",
  },

  // AGENTE IA AVANÇADO
  {
    type: "agenteIA",
    label: "Leader IA",
    icon: Sparkles,
    description: "Coordenador que delega tarefas para Experts",
    category: "Agente IA Avançado",
  },
  {
    type: "agenteIA",
    label: "Expert IA",
    icon: Sparkles,
    description: "Especialista que executa tarefas específicas com IA",
    category: "Agente IA Avançado",
  },
  {
    type: "agenteIA",
    label: "Supervisor",
    icon: Eye,
    description: "Analisa e valida respostas dos Workers",
    category: "Agente IA Avançado",
  },
];
